### ISSUE TITLE
Update Marketplace Fee to 2.25%

### ISSUE THREAD

**Issue by 0xGeel** [kowsheek/nft-gamestop-marketplace-metrics#1]
Hi pal, love the website! 

Here's a bit of feedback: I believe you should increase the fee %. 
Currently you have a 1.25% of volume fee. The UI (image attached) displays a 2.25% fee.

![fees](https://user-images.githubusercontent.com/102362474/178445034-922eb661-ef88-4de4-a5af-c4527a58d60f.png)

**Comment by 0xGeel** [comment]
I was just made aware of the fact that the marketplace fees are split between GME and LRC. I'll close this issue as it's now irrelevant.

I'll do some more probing to see if I can find out the distribution mechanisms once I finish working for the day. If I find something, I'll be sure to re-open this.

**Comment by kowsheek** [comment]
It seems like we should get to the bottom of what the accurate amount is, some folks are saying both the buyer & seller pays to GameStop as well as to Loopring?

Clarity on this would be great!

**Comment by fjelsted** [comment]
I would argue to remove the fees. We simply don't know Gamestop's pricing strategy. Even Matt Furlong said we should look at the revenue. Also, fees might be different depending on the network, e.g. Loopring vs Immutable X.

By showing a fee amount, we're basically misleading and misinforming. Focus on the revenue.

**Comment by 0xGeel** [comment]
@kowsheek we should be able to determine this based on the Loopring transactions.

For example, take this individual that purchased a MetaBoy NFT through the GME platform.
https://lexplorer.io/transactions/24609-147

Buyer's perspective:
`User 74447 bought 1 NFT at 0.05 ETH and paid 0.051 ETH including 0.001 ETH fees`
=> 0.0001 ETH in fees for the buyer

Seller's perspective:
`User 91597 sold 1 NFT at 0.05 ETH and received 0.046375 ETH paying 0.003625 ETH in fees`
=> 0.003625 ETH in fees for the seller


Total: 0,003725 ETH in fees. => **7.45% paid in fees.** 

I believe the royalties for MetaBoys are 5%, so that leaves 2.45% in fees for the network and the marketplace.

I do not know though how these 2.45% in fees are distributed though. Would anyone know how to read that on the Loopring Explorer / Lexplorer?

**Comment by kowsheek** [comment]
Seems like the community is agreeing that 2.25% is the fee: https://www.reddit.com/r/Superstonk/comments/vxn3td/repost_for_user_who_isnt_old_enough_to_post_in/

**Comment by Bilal1200** [comment]
is there any way to integrate game stop wallet with web 3
